### ISSUE TITLE
Crear un formulario para tomar los datos del usuario

### ISSUE THREAD

**Issue by serudda** [sruda/project-course#2]
- [ ] Crear un nuevo componente llamado: FormUser
- [ ] El formulario deberia tener los siguientes campos:
- firstname
- lastname
- email
- phoneNumber
- [ ] Agregar un boton: Save, cuando el usuario lo presione, lo que deberia pasar es que guarda toda esta informacion, y la muestra en una tarjeta estilo presentacion

![screen shot 2017-11-04 at 4 05 42 pm](https://user-images.githubusercontent.com/10075532/32409463-267f0364-c17a-11e7-921c-6cb45d6d6fcf.png)

**NOTA: Mostra 'n' cantidad de tarjetas de presentacion**
**NOTA: Recomiendo usar Flexbox para alinear los componentes**

**Comment by jossee0219** [comment]
Tiempo estimado para terminar la tarea: 6 horas.
Horas al día trabajadas: 1:00 P.M - 7:30 P.M - 6h:30m

**Comment by serudda** [comment]
DONE
